name: Build Vue & Publish to GH Pages
on: 
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'xarantolus'
        reponame: 'numberfact'
        gitemail: "41898282+github-actions[bot]@users.noreply.github.com"
        gitname: "github-actions"
        gitmsg: "Build for GH pages"
        token: ${{ secrets.GITHUB_TOKEN }}
